# -*- coding: utf-8 -*-
"""plate_test_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnxgmF-9qTNKhk5OSv9wzn1FVQTqSNrR
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Ev7WPqjJR8t6T5TXM6Z6")
project = rf.workspace("ed-ret6f").project("matricule_number_detection")
version = project.version(1)
dataset = version.download("yolov11")

# Train YOLO11n on COCO8 for 3 epochs
!yolo train model=yolo11n.pt data= /content/matricule_number_detection-1/data.yaml epochs=100 imgsz=640

# Load YOLO11n, train it on COCO128 for 3 epochs and predict an image with it
from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')  # load a pretrained YOLO detection model
# model.train(data='/content/detection_matricule-1/data.yaml', epochs=100)  # train the model
results = model('/content/matricule_number_detection-1/train/images/11_jpg.rf.bc63b49d6a11686f0939704a810a6e65.jpg', save=True)  # predict on an image